spring.application.name=backend

spring.datasource.url=JDBC:mysql://localhost:3306/food_ordering_app
spring.datasource.username=root
spring.datasource.password=167943@@Qp

spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
